ecommerce/ecommerce/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using static ecommerce.Models.Frontend.FrontHomeModel;
using static ecommerce.Models.FrontMenuModel;
using static ecommerce.Models.FrontProductModel;
using ecommerce.Models.Common;
using ecommerce.Models.Frontend;
using ecommerce.Service;
using ecommerce.Service.BackEndService;
using ecommerce.Service.Front;
using static ecommerce.Models.Frontend.CheckoutModel;
using ecommerce.Service.FrontService;
using System.Data;
using System.Text.RegularExpressions;
using static ecommerce.Models.Backend.BasicMaster;
using ecommerce.Service.EmailService;

namespace ecommerce.Controllers
{
    public class DefaultController : Controller
    {
        public ActionResult Home()
        {
            FrontHomeProductBind model = new FrontHomeProductBind();

            try
            {
                List<FrontHomeProductBind> tempModel = new List<FrontHomeProductBind>();

                Dictionary<int, string> dicMenu = FrontProductService.GetFeaturedMenuList();
                if (dicMenu != null && dicMenu.Count > 0)
                {
                    foreach (var item in dicMenu)
                    {
                        FrontHomeProductBind objModel = new FrontHomeProductBind();
                        List<FrontHomeProductBind> modellist = new List<FrontHomeProductBind>();
                        List<FrontHomeProduct> productList = new List<FrontHomeProduct>();

                        objModel.MenuId = item.Key;
                        objModel.MenuName = item.Value;

                        productList = FrontProductService.GetFrontProductByMenuIdList(item.Key.ToString());
                        if (productList.Count > 0)
                        {
                            objModel.ProductList = productList;
                            tempModel.Add(objModel);
                        }
                    }
                }

                model.FrontHomeProductBindList = tempModel;
            }
            catch (Exception ex)
            {
                ex.ToString();
                throw;
            }
            return View(model);

        }

        public JsonResult HomeAllProductBind(string pincode)
        {
            List<string> result = new List<string>();

            try
            {
                List<MenuModel> menuList = BasicMasterService.GetmenuDetail(null, true).Where(p => p.IsFeatured == true).ToList();

                if (menuList != null && menuList.Count > 0)
                {
                    StringBuilder sbTopCategory = new StringBuilder();
                    StringBuilder sbAllProductMenu = new StringBuilder();
                    StringBuilder sbAllProducts = new StringBuilder();

                    int allProMenuCount = 1;

                    sbTopCategory.Append("<h2>Top Categories</h2><hr>");
                    sbTopCategory.Append("<div class='col-lg-12 col-md-12 col-sm-12 p-0 lm-p-l-0 beyque-p col-xs-12'>");
                    sbTopCategory.Append("<div id='featured_category'>");
                    sbTopCategory.Append("<div class='category_module p-0'>");
                    sbTopCategory.Append("<div id='' class='beyqu-center-column-btn'>");
                    foreach (var menu in menuList)
                    {
                        string menuNameUrl = Regex.Replace(menu.MenuName, @"[^0-9a-zA-Z]+", ",").Replace(",", "-").ToLower();
                        sbTopCategory.Append("<div class='block-cat-wr col-xs-12 col-md-3 pl-5 pr-5'>");
                        sbTopCategory.Append("<a href='/pm/" + menuNameUrl + "/" + menu.Menuid + "'>");
                        sbTopCategory.Append("<img src='" + menu.Image + "' class='img-responsive center-block' alt=''>");
                        sbTopCategory.Append("</a>");
                        sbTopCategory.Append("<h4 class='text-center cat-name-height'>");
                        sbTopCategory.Append("<a href='/pm/" + menuNameUrl + "/" + menu.Menuid + "' class=''>" + menu.MenuName + "</a>");
                        sbTopCategory.Append("</h4>");
                        sbTopCategory.Append("</div>");

                        if (menu.IsFeatured)
                        {
                            //sbAllProductMenu.Append("<ul class='nav nav-tabs collapse footer-collapse text-right' id='cat_tab'>");
                            if (allProMenuCount == 1)
                            {
                                sbAllProductMenu.Append("<li class='active'><a href='#tab-" + allProMenuCount + "' data-toggle='tab'>" + menu.MenuName + "</a></li>");
                            }
                            else
                            {
                                sbAllProductMenu.Append("<li><a href='#tab-" + allProMenuCount + "' data-toggle='tab'>" + menu.MenuName + "</a></li>");
                            }
                            //sbAllProductMenu.Append("</ul>");

                            List<FrontHomeProduct> productList = new List<FrontHomeProduct>();
                            if (!string.IsNullOrEmpty(pincode))
                            {
                                productList = FrontProductService.GetFrontProductByMenuIdList(menu.Menuid.ToString(), pincode);
                            }
                            else
                            {
                                productList = FrontProductService.GetFrontProductByMenuIdList(menu.Menuid.ToString(), pincode);
                            }

                            if (allProMenuCount == 1)
                            {
                                sbAllProducts.Append("<div class='tab-pane fade active in' id='tab-" + allProMenuCount + "'>");
                            }
                            else
                            {
                                sbAllProducts.Append("<div class='tab-pane fade' id='tab-" + allProMenuCount + "'>");
                            }
                            sbAllProducts.Append("<div class='row thummargin'>");
                            //sbAllProducts.Append("<div id='cattab' class='owl-theme'>");                                
                            sbAllProducts.Append("<div id='cattab' class='owl-theme owl-carousel cattabproduct' style='opacity: 1; display: block;'>");

                            sbAllProducts.Append("<div class='owl-wrapper-outer'>");
                            sbAllProducts.Append("<div class='owl-wrapper' style='width: 7854px; left: 0px; display: block;'>");
                            if (productList.Count > 0)
                            {
                                foreach (var product in productList)
                                {
                                    sbAllProducts.Append("<div class='owl-item' style='width: 231px;'>");
                                    sbAllProducts.Append("<div class='product-layout col-xs-12'>");
                                    sbAllProducts.Append("<div class='product-thumb transition'>");
                                    sbAllProducts.Append("<div class='image'>");
                                    if (product.FrontProductImage != null && product.FrontProductImage.Count > 0)
                                    {
                                        sbAllProducts.Append("<a href='" + product.RedirectUrl + "'>");
                                        sbAllProducts.Append("<img src='" + product.FrontProductImage[0].ImageUrl + "' alt='" + product.ProductName + "' title='" + product.ProductName + "' class='img-responsive center-block'>");
                                        sbAllProducts.Append("</a>");
                                    }
                                    if (product.DiscountPer > 0)
                                    {
                                        sbAllProducts.Append("<p class='sale-tag new'>Discount " + product.DiscountPer + "%</p>");
                                    }
                                    sbAllProducts.Append("</div>");
                                    sbAllProducts.Append("<div class='caption text-center'>");
                                    sbAllProducts.Append("<h4>" + product.ProductName + "</h4>");
                                    if (product.DiscountPer > 0)
                                    {
                                        sbAllProducts.Append("<p class='price'><span class='price-new'>" + String.Format("{0:0.00}", product.SalePriceWithDiscount) + "</span> <span class='price-old'>" + product.SalePrice + "</span></p>");
                                    }
                                    else
                                    {
                                        sbAllProducts.Append("<p class='price'><span class='price-new'>" + product.SalePrice + "</span></p>");
                                    }
                                    sbAllProducts.Append("<div class='hidden'>");
                                    sbAllProducts.Append("<span id='frontprodetails_" + product.ProductId + "' class='hidden frontprodetails' data-productid='" + product.ProductId + "' data-productname='" + product.ProductName + "' data-productimgurl='" + (product.FrontProductImage.Count > 0 ? product.FrontProductImage[0].ImageUrl : "~/Content/image/noproduct.png") + "' data-saleprice='" + product.SalePrice + "' data-discountprice='" + product.Discount + "' data-discountper='" + product.DiscountPer + "' data-unitid='" + product.UnitId + "' data-unitname='" + product.UnitName + "'></span>");
                                    sbAllProducts.Append("</div>");
                                    sbAllProducts.Append("<div class='input-group col-xs-12 col-sm-12 qop'>");
                                    sbAllProducts.Append("<label class='control-label col-sm-2 col-xs-2 qlable' for='input-quantity'> Qty </label>");

ecommerce/ecommerce/Views/Default/DirectMenu.cshtml
    <div class="horizontal-menu-wrap">        
        <div class="horizontal-menu">
            <ul class="smartmenu magebig-nav">
                <li class="level0 nav-1 level-top mega_left parent"><a class="level-top" href="#"><span>Rice</span></a></li>
                <li class="level0 nav-1 level-top mega_left parent"><a class="level-top" href="#"><span>Test1</span></a></li>
                <li class="level0 nav-1 level-top mega_left parent"><a class="level-top" href="#"><span>Test2</span></a></li>
                <li class="level0 nav-1 level-top mega_left parent"><a class="level-top" href="#"><span>Test3</span></a></li>
                <li class="level0 nav-1 level-top mega_left parent"><a class="level-top" href="#"><span>Test4</span></a></li>
                <li class="level0 nav-1 level-top mega_left parent"><a class="level-top" href="#"><span>Test5</span></a></li>
            </ul>
        </div>
    </div>

ecommerce/ecommerce/Views/Default/DropdownMenu.cshtml
@model ecommerce.Models.FrontMenuModel.FrontMainCategoryModel

@if (Model.FrontMainCategoryList != null && Model.FrontMainCategoryList.Count > 0)
{
    <ul class="smartmenu magebig-nav">
        @foreach (var menu in Model.FrontMainCategoryList)
        {
            <li class="level0 nav-1 level-top mega_left parent">
                <a href="#" class="level-top"><span>@menu.MenuName</span></a>
                <i class="mbi mbi-ios-arrow-down"></i>
                @if (menu.FrontCategoryList != null && menu.FrontCategoryList.Count > 0)
                {
                    <div class="level0 submenu show-sub" style="width: 527px; height:auto;">
                        <div class="mbmenu-block mbmenu-block-center menu-items col12-12 itemgrid itemgrid-2col">
                            <ul class="level0">
                                @foreach (var category in menu.FrontCategoryList)
                                {
                                    string mymenuurl = System.Text.RegularExpressions.Regex.Replace(menu.MenuName, @"[^0-9a-zA-Z]+", ",");
                                    string mycatuurl = System.Text.RegularExpressions.Regex.Replace(category.CategoryName, @"[^0-9a-zA-Z]+", ",");

                                    <li class="level1 groups item nav-1-1 level-top mega_left parent" style="float: left;">
                                        <a href="/pc/@mymenuurl.ToLower().Replace(",","-")/@menu.MenuId/@mycatuurl.ToLower().Replace(",","-")/@category.CategoryId" class="level-top"><span class="title_group"><span class="fa fa-hand-o-down"></span> @category.CategoryName</span></a>

                                        @if (category.FrontSubCategoryList != null && category.FrontSubCategoryList.Count > 0)
                                        {
                                            <div class="groups-wrapper">
                                                @foreach (var subcategory in category.FrontSubCategoryList)
                                                {
                                                    string mysubcatuurl = System.Text.RegularExpressions.Regex.Replace(subcategory.SubCategoryName, @"[^0-9a-zA-Z]+", ",");
                                                    <ul>
                                                        <li><a href="/pc/@mymenuurl.ToLower().Replace(",","-")/@menu.MenuId/@mycatuurl.ToLower().Replace(",","-")/@category.CategoryId/@mysubcatuurl/@subcategory.SubCategoryId"><span class="fa fa-hand-o-right"></span> @subcategory.SubCategoryName</a></li>

                                                    </ul>
                                                }
                                            </div>
                                        }
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                }
            </li>
        }
    </ul>
}

ecommerce/ecommerce/Views/Default/MenuCatSubCat.cshtml
@model ecommerce.Models.FrontMenuModel.FrontMainCategoryModel

@if (Model.FrontMainCategoryList != null && Model.FrontMainCategoryList.Count > 0)
{
    <ul class="nav">
        @foreach (var menu in Model.FrontMainCategoryList)
        {
            string urlmenuname = System.Text.RegularExpressions.Regex.Replace(menu.MenuName, @"[^0-9a-zA-Z]+", ",").ToLower().Replace(",", "-");

            <li class="dropdown moremenu">
                <a href="/pm/@urlmenuname/@menu.MenuId" class="dropdown-toggle header-menu" data-toggle="dropdown">
                    <div class="menu-img pull-left">
                        <img src="@menu.Image" alt="@menu.MenuName">
                    </div>@menu.MenuName
                    @if (menu.FrontCategoryList != null && menu.FrontCategoryList.Count > 0)
                    {
                        <i class="fa fa-angle-down pull-right enangle"></i>
                    }
                </a>
                @if (menu.FrontCategoryList != null && menu.FrontCategoryList.Count > 0)
                {
                    <div class="dropdown-menu">
                        <div class="dropdown-inner">
                            @foreach (var category in menu.FrontCategoryList)
                            {
                                string urlcatname = System.Text.RegularExpressions.Regex.Replace(category.CategoryName, @"[^0-9a-zA-Z]+", ",").ToLower().Replace(",", "-");
                                <ul class="list-unstyled">
                                    <li class="dropdown-submenu">
                                        <a href="/pc/@urlmenuname/@menu.MenuId/@urlcatname/@category.CategoryId" class="submenu-title"> @category.CategoryName </a>
                                        @if (category.FrontSubCategoryList != null && category.FrontSubCategoryList.Count > 0)
                                        {
                                            <ul class="list-unstyled grand-child">
                                                @foreach (var subcategory in category.FrontSubCategoryList)
                                                {
                                                    string urlsubcatname = System.Text.RegularExpressions.Regex.Replace(subcategory.SubCategoryName, @"[^0-9a-zA-Z]+", ",").ToLower().Replace(",", "-");
                                                    <li><a href="/psc/@urlmenuname/@menu.MenuId/@urlcatname/@category.CategoryId/@urlsubcatname/@subcategory.SubCategoryId"> @subcategory.SubCategoryName </a> </li>
                                                }
                                            </ul>
                                        }
                                    </li>
                                </ul>
                            }
                        </div>
                    </div>
                }
            </li>
        }
    </ul>
}

@*<li class="dropdown moremenu">
    <a href="#" class="dropdown-toggle header-menu" data-toggle="">
        <div class="menu-img pull-left">
            <img src="/Content/NewfrontEnd/image/catalog/menu-icon/R-190x140.png" alt="Rice &amp; Grains">
        </div>Rice &amp; Grains<i class="fa fa-angle-down pull-right enangle"></i>
    </a>
    <div class="dropdown-menu" style="margin-left: -172px;">
        <div class="dropdown-inner">
            <ul class="list-unstyled">
                <li class="dropdown-submenu">
                    <a href="#" class="submenu-title"> Mice and Trackballs (17) </a>
                </li>
                <li class="dropdown-submenu">
                    <a href="#" class="submenu-title"> Monitors (18) </a>
                    <ul class="list-unstyled grand-child">
                        <li><a href="#"> test 1 (0) </a> </li>
                        <li><a href="3"> test 2 (0) </a> </li>
                    </ul>
                </li>
            </ul>
            <ul class="list-unstyled">
                <li class="dropdown-submenu">
                    <a href="#" class="submenu-title"> Printers (16) </a>
                    <ul class="list-unstyled grand-child">
                        <li><a href="#"> Scanners (13) </a> </li>
                        <li><a href="#"> Web Cameras (14) </a> </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</li>*@

ecommerce/ecommerce/Views/Default/MobileMenuCatSubCat.cshtml
@model ecommerce.Models.FrontMenuModel.FrontMainCategoryModel

@if (Model.FrontMainCategoryList != null && Model.FrontMainCategoryList.Count > 0)
{
    <ul class="nav navbar-nav">
        @foreach (var menu in Model.FrontMainCategoryList)
        {
            string urlmenuname = System.Text.RegularExpressions.Regex.Replace(menu.MenuName, @"[^0-9a-zA-Z]+", ",").ToLower().Replace(",", "-");

            <li class="dropdown">
                <a href="/pm/@urlmenuname/@menu.MenuId" class="dropdown-toggle header-menu" data-toggle="dropdown" aria-expanded="true">
                    @menu.MenuName
                    @if (menu.FrontCategoryList != null && menu.FrontCategoryList.Count > 0)
                    {
                        <i class="fa fa-angle-down pull-right"></i>
                    }
                </a>
                @if (menu.FrontCategoryList != null && menu.FrontCategoryList.Count > 0)
                {
                    <div class="dropdown-menu">
                        <div class="dropdown-inner">
                            @foreach (var category in menu.FrontCategoryList)
                            {
                                string urlcatname = System.Text.RegularExpressions.Regex.Replace(category.CategoryName, @"[^0-9a-zA-Z]+", ",").ToLower().Replace(",", "-");
                                <ul class="list-unstyled">
                                    <li class="dropdown-submenu">
                                        <a href="/pc/@urlmenuname/@menu.MenuId/@urlcatname/@category.CategoryId" class="submenu-title"> @category.CategoryName </a>
                                        @if (category.FrontSubCategoryList != null && category.FrontSubCategoryList.Count > 0)
                                        {
                                            <ul class="list-unstyled grand-child">
                                                @foreach (var subcategory in category.FrontSubCategoryList)
                                                {
                                                    string urlsubcatname = System.Text.RegularExpressions.Regex.Replace(subcategory.SubCategoryName, @"[^0-9a-zA-Z]+", ",").ToLower().Replace(",", "-");
                                                    <li><a href="/pc/@urlmenuname/@menu.MenuId/@urlcatname/@category.CategoryId/@urlsubcatname/@subcategory.SubCategoryId"> @subcategory.SubCategoryName </a> </li>
                                                }
                                            </ul>
                                        }
                                    </li>
                                </ul>
                            }
                        </div>                        
                    </div>
                }
            </li>
        }
    </ul>
}

ecommerce/ecommerce/Views/Default/NewProduct.cshtml
@model ecommerce.Models.FrontProductModel.FrontProduct

@{
    ViewBag.Title = "NewProduct";
    Layout = "~/Views/Shared/_NewFrontMaster.cshtml";
}

@section header
{

}

@*@if (Model.FrontProductList != null && Model.FrontProductList.Count > 0)
    {*@
<div id="product-category" class="container common-shed">
    <ul class="breadcrumb">
        @*<li><a href="/"><i class="fa fa-home"></i></a></li>
        <li><a href="#">krishna</a></li>*@
    </ul>
    <div class="row">

        <aside id="column-left" class="col-md-3 col-sm-4 col-xs-12">
            @*<div class="list-group cateleft">
                    @Html.Action("ProductSideMenu", "Default")
                </div>*@
            <div id="tf-filter" class="panel tf-filter panel-default">
                <div class="panel-heading clearfix">
                    <h4 class="panel-title pull-left">Filter</h4>
                    <span data-tf-reset="all" class="tf-filter-reset pull-right hidden label label-info filteractivated"><i class="fa fa-refresh"></i> Clear all</span>
                </div>                
                <div class="tf-list-filter-group leftsidefilter"> </div>
            </div>
        </aside>

        <div id="content" class="col-xs-12 col-sm-8 col-md-9 col-lg-9">

            @*<div class="inspdes">
                    <h2>@Model.FrontProductList[0].MenuName</h2>
                </div>*@
            <div class="row cate-border proupsortby" style="margin: 0px 0px 15px!important;">
                <div class="col-md-2 col-sm-3 col-xs-3 catebt">
                    <div class="btn-group-sm">
                        <button type="button" id="list-view" class="btn inslistgrid" data-toggle="tooltip" title="" data-original-title="List">
                            <img src="~/Content/NewfrontEnd/image/catalog/category/list.png">
                        </button>
                        <button type="button" id="grid-view" class="btn inslistgrid active" data-toggle="tooltip" title="" data-original-title="Grid">
                            <img src="~/Content/NewfrontEnd/image/catalog/category/grid.png">
                        </button>
                    </div>
                </div>
                <div class="col-lg-4 col-md-5 col-xs-5 col-sm-5 sorting pull-right">
                    <div class="input-group input-group-sm">
                        <label class="input-group-addon" for="input-sort">Sort By:</label>
                        <select id="input-sort" class="form-control" onchange="location = this.value;">
                            <option value="#" selected="selected">Default</option>
                            <option value="#">Name (A - Z)</option>
                            <option value="#">Name (Z - A)</option>
                            <option value="#">Price (Low &gt; High)</option>
                            <option value="#">Price (High &gt; Low)</option>
                            <option value="#">Rating (Highest)</option>
                            <option value="#">Rating (Lowest)</option>
                            <option value="#">Model (A - Z)</option>
                            <option value="#">Model (Z - A)</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="row text-center noproductlocation"></div>
            <div class="row catebg bindproductlist"></div>
        </div>
    </div>
</div>
@*}
    else
    {
        <img src="~/Content/image/noproduct.png" class="img-responsive" />
    }*@

<button type="button" class="btn btn-info btn-lg filteractivation hidden" data-backdrop="static" data-keyboard="false" data-toggle="modal" data-target="#FilterActivation"></button>
<div class="modal fade" id="FilterActivation" role="dialog">
    <div class="modal-dialog modal-sm" style="margin:15% auto!important;">
        <!-- Modal content-->
        <div class="modal-content" style="text-align: center;border-radius: 5px !important;">
            <div class="modal-body" style="height:0px!important;">
                <img src="~/Content/NewfrontEnd/image/catalog/loader.gif" style="border-radius: 20px; width: 200px;" />
            </div>
            <div class="modal-footer hidden">
                <button type="button" class="btn btn-danger hidden closefilteractivation" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

@section footer{
    <script src="~/Content/NewfrontEnd/js/newproductpage.js"></script>
    <script>
        $(function () {
            if (window.innerWidth < 767) { // Collaped all panel in small device
                $('#tf-filter .collapse.in').collapse("hide");
            }
        });
    </script>
    <style>
        .tf-filter-group {
            border-bottom: 1px solid #ddd;
            background: white;
        }

            .tf-filter-group:last-child {
                border-bottom: 0px;
            }

        .tf-filter-group-header {
            /*border-bottom: 1px solid #ddd;*/
            padding: 15px;
        }

            .tf-filter-group-header.collapsed {
                border: none;
            }

        .tf-filter-group-title {
            text-transform: uppercase;
        }

        .tf-filter-group-content, .tf-filter-group-search {
            padding: 8px 15px;
            display: block;
        }

        .tf-filter-group-content {
            max-height: 200px;
            overflow-y: auto;
            padding-bottom: 15px;
        }

        .tf-filter-reset {
            cursor: pointer;
            margin-left: 15px;
        }

        .tf-filter-group-header.collapsed .fa-caret-up:before {
            content: "\f0d7";
        }

        .tf-filter-group-content .form-check-input {
            margin: 0 5px 0 0;
        }

        .tf-filter-group-content .form-check.both input, .tf-filter-group-content .form-check.image input {
            display: none;
        }

        .tf-filter-group-content .form-check.image {
            display: inline-block;
        }

        .tf-filter-group-content .form-check img {
            border: 1px solid transparent;
            padding: 1px;
            border-radius: 5px;
            cursor: pointer;
            margin-right: 5px;
        }

        .tf-filter-group-content .form-check input:checked + img {
            border-color: #2096c3;
            box-shadow: 0px 0px 5px #2096c3;
        }

        .tf-filter-group-content .form-check input:disabled + img {
            opacity: 0.5;
        }

        .tf-filter-group-search {
            position: relative;
        }

            .tf-filter-group-search .fa {
                position: absolute;
                color: #adadad;
            }

            .tf-filter-group-search input {
                width: 100%;
                border: none;
                border-bottom: 1px solid #ddd;
                padding: 0 0 0 18px;
                margin: 0;
                height: auto;
                border-radius: 0;
            }

                .tf-filter-group-search input:focus {
                    border: none;
                    border-bottom: 1px solid #bdbdbd;
                }

        .tf-loader {
            position: absolute;
            width: 100%;
            height: 100%;
            text-align: center;
            background: #ddd;
            opacity: 0.5;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            z-index: 99;
        }

            .tf-loader > * {
                margin-top: 50%;
                font-size: 40px;
                transform: translateY(-50%);
            }

        .tf-filter-loading {
            cursor: wait;
        }

        .tf-filter-group-content .ui-slider {
            margin-bottom: 8px;
        }

        #column-left, #column-right {
            display: block !important;
        }
    </style>
}

ecommerce/ecommerce/Views/Default/ProductSideMenu.cshtml
@model ecommerce.Models.FrontMenuModel.FrontMainCategoryModel

@if (Model.FrontMainCategoryList != null && Model.FrontMainCategoryList.Count > 0)
{
    foreach (var menu in Model.FrontMainCategoryList)
    {
        string[] path = HttpContext.Current.Request.Url.AbsolutePath.Split('/');

        string urlmenuname = System.Text.RegularExpressions.Regex.Replace(menu.MenuName, @"[^0-9a-zA-Z]+", ",").ToLower().Replace(",", "-");

        if (path[2].ToLower().Trim() == urlmenuname.Trim())
        {
            <a href="/pm/@urlmenuname/@menu.MenuId" class="list-group-item active">@menu.MenuName </a>
        }
        else
        {
            <a href="/pm/@urlmenuname/@menu.MenuId" class="list-group-item">@menu.MenuName </a>
        }
    }
}

ecommerce/ecommerce/Views/Default/TopCategories.cshtml
@model ecommerce.Models.FrontMenuModel.FrontMainCategoryModel

@if (Model.FrontMainCategoryList != null && Model.FrontMainCategoryList.Count > 0)
{
    <div class="container">
        <div class="cat-img">
            <div class="pro-bg pro-nepr">
                <h2>Top Categories</h2><hr>
                <div class="col-lg-12 col-md-12 col-sm-12 p-0 lm-p-l-0 beyque-p col-xs-12">
                    <div id="featured_category">
                        <div class="category_module p-0">
                            <div id="" class="beyqu-center-column-btn">
                                @foreach (var menu in Model.FrontMainCategoryList)
                                {
                                    string urlmenuname = System.Text.RegularExpressions.Regex.Replace(menu.MenuName, @"[^0-9a-zA-Z]+", ",").ToLower().Replace(",", "-");
                                    <div class="block-cat-wr col-xs-12 col-md-3 pl-5 pr-5">
                                        <a href="/pm/@urlmenuname/@menu.MenuId">
                                            <img src="@menu.Image" class="img-responsive center-block" alt="">
                                        </a>
                                        <h4 class="text-center cat-name-height">
                                            <a href="/pm/@urlmenuname/@menu.MenuId" class="">@menu.MenuName</a>
                                        </h4>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}